### ISSUE TITLE
[marketing] create a book contests

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/getrector.org#261]
## Todo Michal

- [ ] prepare contest text
- [ ] put it on Twitter
- [ ] put it on FB
- [ ] send to winners

## Todo 

- [ ] pick winners

## Todo Tomas

- [ ] put contest post on blog

**Comment by aLmonndo** [comment]
6 winners:

Alexey Berezuev
Sebastian Schreiber
Simon Schubert
Adamo Crespi
Alfred Bez
Alister

- [ ] check relevancy of winners' posts before contact

**Comment by aLmonndo** [comment]
Spreadshit of Pros and Cons:
https://docs.google.com/spreadsheets/d/1OCeJGRYDpJlaommA_vNQnx63jX_MA1INH4Nj2M-11-w/edit#gid=0
